### ISSUE TITLE
菜鸟求助

### ISSUE THREAD

**Issue by qw52655265** [neroneroffy/react-music-webapp#3]
请问楼主server该如何启动，我只会Client端npm start.
刚接触React，对命令这些都不太熟悉，望指教。

**Comment by capslocktao** [comment]
可以cd 到server目录下的bin文件夹下。node www.js或者webstorm的菜单栏上的run菜单，选择Edit Configurations 点击+，选择bin目录下的www文件，然后每次就不用输入命令启动了

**Comment by 290068483** [comment]
为什么不写在readme.md里面

**Comment by 290068483** [comment]
我cd 到server 里面npm run  start ，就卡到那里不动，什么都不做

**Comment by 290068483** [comment]
你这个是不是先启动server ，你这个nodejs能起来，问题是没提示。再cd 到client npm run start。感觉你说明文件没写清楚

**Comment by neroneroffy** [comment]
确实是我这个项目结构和README没写清楚，我这个当时是打算开发后台的，但是后来搁置了，client才是真正的应用，现在数据都是json文件模拟的，不需要server。所以另外两个文件夹目前没用。抱歉。。

**Comment by neroneroffy** [comment]
> 你这个是不是先启动server ，你这个nodejs能起来，问题是没提示。再cd 到client npm run start。感觉你说明文件没写清楚

确实是我这个项目结构和README没写清楚，我这个当时是打算开发后台的，但是后来搁置了，client才是真正的应用，现在数据都是json文件模拟的，不需要server。所以另外两个文件夹目前没用。抱歉。。

**Comment by lizhaohong** [comment]
你好，楼主，我发现在client文件夹 npm run start之后，启动是启动了，但是很多你mock的数据都没有诶，和你的示范gif表现不一样😂

**Comment by neroneroffy** [comment]
@lizhaohong  我已经修复提交了，你更新下代码就可以了

**Comment by neroneroffy** [comment]
@lizhaohong 我修复了，提交上去了，你更新下代码
